// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7IlHAWqnlP6A-TdT9K_1VkovXsWSCkRs',
    appId: '1:120110736637:web:d2dd6684f93915feb30a94',
    messagingSenderId: '120110736637',
    projectId: 'fir-database-2d731',
    authDomain: 'fir-database-2d731.firebaseapp.com',
    databaseURL: 'https://fir-database-2d731-default-rtdb.firebaseio.com',
    storageBucket: 'fir-database-2d731.appspot.com',
    measurementId: 'G-G0CVNRXK4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaE1XuKyVK131vV-llmsUZzLrOeN-zWfM',
    appId: '1:120110736637:android:76014e7aa4b7f280b30a94',
    messagingSenderId: '120110736637',
    projectId: 'fir-database-2d731',
    databaseURL: 'https://fir-database-2d731-default-rtdb.firebaseio.com',
    storageBucket: 'fir-database-2d731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8FjeGnTPtX5g47AtfwapOw5W_9mTOsHw',
    appId: '1:120110736637:ios:347f1e5be72f8fc3b30a94',
    messagingSenderId: '120110736637',
    projectId: 'fir-database-2d731',
    databaseURL: 'https://fir-database-2d731-default-rtdb.firebaseio.com',
    storageBucket: 'fir-database-2d731.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8FjeGnTPtX5g47AtfwapOw5W_9mTOsHw',
    appId: '1:120110736637:ios:347f1e5be72f8fc3b30a94',
    messagingSenderId: '120110736637',
    projectId: 'fir-database-2d731',
    databaseURL: 'https://fir-database-2d731-default-rtdb.firebaseio.com',
    storageBucket: 'fir-database-2d731.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7IlHAWqnlP6A-TdT9K_1VkovXsWSCkRs',
    appId: '1:120110736637:web:d9cb11d225f98e98b30a94',
    messagingSenderId: '120110736637',
    projectId: 'fir-database-2d731',
    authDomain: 'fir-database-2d731.firebaseapp.com',
    databaseURL: 'https://fir-database-2d731-default-rtdb.firebaseio.com',
    storageBucket: 'fir-database-2d731.appspot.com',
    measurementId: 'G-CP29ZMWME7',
  );
}
